### ISSUE TITLE
Verify that present repo can bit-for-bit reproduce ACME initial conditions

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/geometric_features#61]
We need to make sure the recent changes in the repo haven't broken our ability to recreate existing ACME initial conditions exactly.  This means performing all existing `init_step1` in `global_ocean` test cases both with `master` and with an earlier version of `master` before #52 was merged.

**Comment by xylar** [comment]
I will try to do this tomorrow.

**Comment by xylar** [comment]
# Testing

I performed `init_step1` of the following `global_ocean` test cases:
```
EC_60to30km/default
EC_60to30km/with_land_ice
QU_120km/default
QU_120km/with_land_ice
QU_240km/default
QU_240km/with_land_ice
QU_480km/default
RRS_30to10km/default
RRS_30to10km/with_land_ice
```
once using the `geometric_features` from 9e469ebd286bbc5c10721b387f382e53580708b2 (the current `origin/master`) and once using c97f8c6b05c76c2847e4d562bcb6e33c0b32892d (before changes were made to the way `geojson` files are written out in this repo).

I verified that `xCell` in `culled_mesh_final.nc` and `transectCellMasks` in `critical_passages_mask_final.nc` were bit-for-bit identical between initial conditions based on these two versions of `geometric_features`.  This should ensure that the number of cells has not changed, that the cells are at identical locations (at least in the x direction) and that critical passages are affecting the same cells as before, which should be the only ways that this repo can affect the MPAS-O initial conditions.

I tried to run `RRS_15to5km/default` but it crashed with the following error message on the wolf login nodes:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Traceback (most recent call last):
  File "./init_step1.py", line 70, in <module>
    '-f', 'land_coverage.geojson'], env=os.environ.copy())
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/default-2.7/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./MpasMaskCreator.x', 'base_mesh.nc', 'land_mask.nc', '-f', 'land_coverage.geojson']' returned non-zero exit status -6
Traceback (most recent call last):
  File "./run.py", line 12, in <module>
    subprocess.check_call(['./init_step1.py', '-p', 'geometric_features'], env=os.environ.copy())
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/default-2.7/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./init_step1.py', '-p', 'geometric_features']' returned non-zero exit status 1
```
presumably a memory issue.

As far as I am aware, no other components use geometric features to create their initial conditions, so I am satisfied that we can still exactly reproduce existing ACME initial conditions.  I will therefore close this issue.
